#!/bin/bash

# Lists files taking up the most space
dutop() {
  local fp="/"
  local amount=20

  # Parse options
  while getopts ":p:n:h" opt; do
    case $opt in
    p) fp="$OPTARG" ;;
    n) amount="$OPTARG" ;;
    h)
      echo "Description: List items taking up the most disk space."
      echo "Usage: dutop [-p path] [-n amount]"
      return 0
      ;;
    \?)
      echo "Invalid option -$OPTARG" >&2
      return 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      return 1
      ;;
    esac
  done

  if [ ! -d "$fp" ]; then
    echo "'$fp' is not a valid directory."
    return 1
  fi

  if ! [[ "$amount" =~ ^[0-9]+$ ]]; then
    echo "'$amount' is not a valid number."
    return 1
  fi

  sudo du -hax "$fp" | sort -rh | head -n"$amount"
}

# List explicitly installed packages
lsxp() {
  local explicit=$(mktemp)
  local aur=$(mktemp)

  sudo pacman -Qqe | sort >"$explicit"
  sudo pacman -Qqm | sort >"$aur"

  # Compare and output the result
  comm -23 "$explicit" "$aur"

  # Clean up temporary files
  rm "$explicit" "$aur"
}

# Change directory to repo after lazygit
lg()
{
    export LAZYGIT_NEW_DIR_FILE=~/.lazygit/newdir

    lazygit "$@"

    if [ -f $LAZYGIT_NEW_DIR_FILE ]; then
            cd "$(cat $LAZYGIT_NEW_DIR_FILE)"
            rm -f $LAZYGIT_NEW_DIR_FILE > /dev/null
    fi
}

# Change directory with yazi
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp" > /dev/null
}
