# Prevent apps from maximizing themselves
windowrule = suppress_event maximize, match:class .*

# Default opacity (unless overridden)
windowrule = opacity 0.97 0.9, match:class .*

windowrule = float on, match:title ^(navi)$
windowrule = stay_focused on, match:title ^(navi)$
windowrule = size 50% 50%, match:title ^(navi)$

# Tag all games
windowrule = tag +games, match:class ^(gamescope)$
windowrule = tag +games, match:class ^(steam_proton)$
windowrule = tag +games, match:class ^(steam_app_.*)$

windowrule = tag -games, match:title Battle\.net

# Set rules for games
windowrule = workspace 2, match:tag games*
windowrule = no_blur on, match:tag games*
windowrule = fullscreen on, match:tag games*
